framework:
    session:
        enabled: true
        handler_id: null

    secret: '%env(APP_SECRET)%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
