framework:
    session:
        enabled: true
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        gc_maxlifetime: 3600
        gc_probability: 1
        gc_divisor: 100

    secret: '%env(APP_SECRET)%'
    csrf_protection:
        enabled: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
