security:
    # Configuration des hashers de mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Configuration des providers d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\TUserUsr  # Assure-toi que cette classe existe et est correcte
                property: email  # Assure-toi que l'attribut email existe dans l'entité TUserUsr

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginAuthenticator
            logout:
                path: app_logout
                
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_page_tableau_scores

            entry_point: form_login

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
