security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
        
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginAuthenticator
            
            entry_point: form_login
            form_login:
                enable_csrf: true
                csrf_parameter: _csrf_token
                csrf_token_id: authenticate
                login_path: app_login
                check_path: app_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
            logout:
                path: app_logout
                target: app_login
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH, parameter: _switch_user }      


    access_control:
        - { path: ^/$, roles: PUBLIC_ACCESS }  # Permettre l'accès à la page d'accueil
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ORGA: [ROLE_USER]
