controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

import_scores:
    path: /import-scores
    controller: App\Controller\ScoreController::importScores

app_admin_impersonate:
    path: /admin/impersonate
    controller: App\Controller\AdminController::impersonate

_locale:
    path: /{_locale}/
    requirements:
        _locale: 'fr|en'
    defaults:
        _locale: 'fr'
    options:
        expose: true
