controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

import_scores:
    path: /import-scores
    controller: App\Controller\ScoreController::importScores
