-- Insert sample competitions
INSERT INTO T_COMPETITION_CMP (CMP_ADDRESS, CMP_DATE_BEGIN, CMP_DATE_END, CMP_NAME, CMP_DESC)
VALUES ('123 Main St', '2025-01-01', '2025-01-10', 'Winter Championship', 'Annual winter event');

INSERT INTO T_COMPETITION_CMP (CMP_ADDRESS, CMP_DATE_BEGIN, CMP_DATE_END, CMP_NAME, CMP_DESC)
VALUES ('456 Elm St', '2025-02-01', '2025-02-10', 'Spring Championship', 'Annual spring event');

-- Insert sample users
INSERT INTO T_USER_USR (USR_TYPE, USR_MAIL, USR_PASS, USR_CREATION_DATE)
VALUES ('ADMIN', 'admin@example.com', 'securepassword', '2025-01-01');

INSERT INTO T_USER_USR (USR_TYPE, USR_MAIL, USR_PASS, USR_CREATION_DATE)
VALUES ('USER', 'user1@example.com', 'password123', '2025-01-02');

INSERT INTO T_USER_USR (USR_TYPE, USR_MAIL, USR_PASS, USR_CREATION_DATE)
VALUES ('USER', 'user2@example.com', 'password123', '2025-01-02');

-- Insert sample teams
INSERT INTO T_TEAM_TEM (USR_ID, TEM_NAME, TEM_CREATION_DATE, CMP_ID)
VALUES (2, 'Blue Warriors', '2025-01-05', 1);

INSERT INTO T_TEAM_TEM (USR_ID, TEM_NAME, TEM_CREATION_DATE, CMP_ID)
VALUES (3, 'Green Giants', '2025-01-06', 2);

-- Insert sample fields
INSERT INTO T_FIELD_FLD (CMP_ID, FLD_NAME)
VALUES (1, 'Field A');

-- Insert sample members
INSERT INTO T_MEMBER_MBR (TEM_ID, MBR_NAME, MBR_SURNAME, MBR_MAIL)
VALUES (1, 'John', 'Doe', 'john.doe@example.com');

INSERT INTO T_MEMBER_MBR (TEM_ID, MBR_NAME, MBR_SURNAME, MBR_MAIL)
VALUES (2, 'Jane', 'Smith', 'jane.smith@example.com');

-- Insert sample championships
INSERT INTO T_CHAMPIONSHIP_CHP (CMP_ID)
VALUES (1);

-- Insert sample tournaments
INSERT INTO T_TOURNAMENT_TNM (CMP_ID)
VALUES (1);

-- Insert sample encounters
INSERT INTO T_ENCOUNTER_ENC (TNM_ID, CHP_ID, FLD_ID, TEM_ID_BLUE, TEM_ID_GREEN, ENC_STATE, ENC_DATE_BEGIN, ENC_DATE_END, ENC_SCORE_BLUE, ENC_SCORE_GREEN)
VALUES (1, 1, 1, 1, 2, 'CONCLUE', '2025-01-07 10:00:00', '2025-01-07 12:00:00', 3, 1);
